In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'C:\\Users\\LOQ 15\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
n = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8], 
               [9, 10, 11, 12]])
n[1:2]

array([[5, 6, 7, 8]])

In [12]:
n[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [14]:
np.random.seed(2)
np.random.randn(0,10,5)

array([], shape=(0, 10, 5), dtype=float64)

In [15]:
a = np.arange(8)
a + 1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
b = (10 + (a*2) ** 2/ 100)
b

array([10.  , 10.04, 10.16, 10.36, 10.64, 11.  , 11.44, 11.96])

In [17]:
a > b

array([False, False, False, False, False, False, False, False])

In [18]:
a [a > b]

array([], dtype=int32)